version: "3.9"

services: 
    db:
        image: postgres
        volumes: 
            - db_volume:/var/lib/postgresql/data
        env_file: 
            - ./config/.env
        expose: 
            - "5432"
    bot:
        build: .
        volumes: 
            - ./:/vkbottle-cm
        depends_on: 
            - db
volumes: 
    db_volume:
