"""Added user model

Revision ID: 20317f955e85
Revises: d271b861c94e
Create Date: 2021-05-07 19:28:02.775009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20317f955e85'
down_revision = 'd271b861c94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
